# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestExercice3():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_parcourirlescatgories(self):
    self.driver.get("https://www.demoblaze.com/")
    self.driver.set_window_size(788, 816)
    self.driver.find_element(By.ID, "itemc").click()
    self.driver.find_element(By.LINK_TEXT, "Laptops").click()
    self.driver.find_element(By.LINK_TEXT, "Monitors").click()
  
  def test_ajouterunproduitaupanier(self):
    self.driver.get("https://www.demoblaze.com/")
    self.driver.set_window_size(788, 816)
    self.driver.find_element(By.LINK_TEXT, "Samsung galaxy s6").click()
    self.driver.find_element(By.LINK_TEXT, "Add to cart").click()
    assert self.driver.switch_to.alert.text == "Product added"
  
  def test_accderaupaniervrifierlesarticlesajoutsetsupprimerensincessaire(self):
    self.driver.get("https://www.demoblaze.com/")
    self.driver.set_window_size(788, 816)
    self.driver.find_element(By.ID, "cartur").click()
    self.driver.find_element(By.LINK_TEXT, "Delete").click()
  
  def test_vrifierlaconfirmationdelacommandeaprslepaiement(self):
    self.driver.get("https://www.demoblaze.com/")
    self.driver.set_window_size(788, 816)
    self.driver.find_element(By.ID, "cartur").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("user")
    self.driver.find_element(By.ID, "country").click()
    self.driver.find_element(By.ID, "country").send_keys("Tunisia")
    self.driver.find_element(By.ID, "city").click()
    self.driver.find_element(By.ID, "city").send_keys("Tunis")
    self.driver.find_element(By.ID, "card").click()
    self.driver.find_element(By.ID, "card").send_keys("123456789")
    self.driver.find_element(By.ID, "month").click()
    self.driver.find_element(By.ID, "month").send_keys("January")
    self.driver.find_element(By.ID, "year").click()
    self.driver.find_element(By.ID, "year").send_keys("2024")
    self.driver.find_element(By.CSS_SELECTOR, ".modal-open").click()
    self.driver.find_element(By.CSS_SELECTOR, "#orderModal .btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".confirm").click()
  
  def test_explorerlespagessupplmentaires(self):
    self.driver.get("https://www.demoblaze.com/")
    self.driver.set_window_size(787, 816)
    self.driver.find_element(By.LINK_TEXT, "Contact").click()
    self.driver.find_element(By.CSS_SELECTOR, "#exampleModal span").click()
    self.driver.find_element(By.LINK_TEXT, "About us").click()
    self.driver.find_element(By.CSS_SELECTOR, ".vjs-poster").click()
    self.driver.find_element(By.CSS_SELECTOR, "#videoModal .btn").click()
    self.driver.find_element(By.ID, "login2").click()
    self.driver.find_element(By.CSS_SELECTOR, "#logInModal .btn-secondary").click()
    self.driver.find_element(By.ID, "signin2").click()
    self.driver.find_element(By.CSS_SELECTOR, "#signInModal .btn-secondary").click()
  
